# Generated by Django 6.0.5 on 2026-05-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='محل ورد وشوكولاته', max_length=200)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('currency_symbol', models.CharField(default='ريال', max_length=10)),
            ],
            options={
                'verbose_name': 'إعدادات المحل',
                'verbose_name_plural': 'إعدادات المحل',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('flower', 'ورد'), ('chocolate', 'شوكولاته'), ('gift', 'هدايا'), ('accessory', 'إكسسوارات')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name_plural': 'التصنيفات',
            },
        ),
    ]
