# Generated by Django 6.0.5 on 2026-05-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_name',
            field=models.CharField(default='ROOTS FLOWERS', max_length=200),
        ),
    ]
