# Generated by Django 6.0.5 on 2026-05-22 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'فئة مصروف', 'verbose_name_plural': 'فئات المصروفات'},
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('card', 'بطاقة')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='رقم الإيصال أو الفاتورة', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='category_type',
            field=models.CharField(choices=[('operational', 'تشغيلية'), ('maintenance', 'صيانة'), ('supplies', 'لوازم'), ('rent', 'إيجار'), ('salaries', 'رواتب'), ('utilities', 'فواتير خدمات'), ('marketing', 'تسويق'), ('transport', 'نقل وتوصيل'), ('other', 'أخرى')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='color',
            field=models.CharField(default='primary', help_text='لون Bootstrap', max_length=20),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(default='fas fa-receipt', help_text='أيقونة Font Awesome', max_length=50),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
