# Generated by Django 6.0.5 on 2026-05-22 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSaleQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('sync_attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'مبيعات دون اتصال',
                'verbose_name_plural': 'مبيعات دون اتصال',
                'ordering': ['created_at'],
            },
        ),
    ]
